import { useEffect, useState } from "react";
import api from "../../services/api";
import Loader from "./Loader";
import { toast } from "react-toastify";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

import "../styles/Reports.css";

function Reports() {

    const [loading, setLoading] = useState(true);

    const [report, setReport] = useState({
        totalUsers: 0,
        totalDoctors: 0,
        totalPatients: 0,
        totalAppointments: 0,
        totalBills: 0,
        totalRevenue: 0,
        paidBills: 0,
        pendingBills: 0,
    });

    // =====================================================
    // Fetch Reports
    // =====================================================

    useEffect(() => {
        fetchReports();
    }, []);

    const fetchReports = async () => {

        try {

            setLoading(true);

            const token = localStorage.getItem("token");

            const res = await api.get("/analytics", {
                headers: {
                    Authorization: `Bearer ${token}`,
                },
            });

            setReport(
                res.data.analytics || {
                    totalUsers: 0,
                    totalDoctors: 0,
                    totalPatients: 0,
                    totalAppointments: 0,
                    totalBills: 0,
                    totalRevenue: 0,
                    paidBills: 0,
                    pendingBills: 0,
                }
            );

        } catch (error) {

            console.error("Reports Error:", error);

            toast.error(
                error.response?.data?.message ||
                "Failed to Load Reports"
            );

        } finally {

            setLoading(false);

        }

    };


    // =====================================================
    // PDF DATA
    // =====================================================

    const getReportData = () => {

        return [
            ["Total Users", report.totalUsers],
            ["Total Doctors", report.totalDoctors],
            ["Total Patients", report.totalPatients],
            ["Total Appointments", report.totalAppointments],
            ["Total Bills", report.totalBills],
            ["Total Revenue", `₹ ${report.totalRevenue}`],
            ["Paid Bills", report.paidBills],
            ["Pending Bills", report.pendingBills],
        ];

    };


    // =====================================================
    // Export PDF
    // =====================================================

    const exportPDF = () => {

        try {

            const doc = new jsPDF();

            // Header
            doc.setFontSize(20);

            doc.text(
                "Medlora Hospital Management",
                14,
                20
            );

            doc.setFontSize(12);

            doc.text(
                "Hospital Analytics & Summary Report",
                14,
                28
            );

            // Table
            autoTable(doc, {

                startY: 38,

                head: [
                    ["Category", "Value"]
                ],

                body: getReportData(),

                theme: "grid",

                styles: {
                    fontSize: 11,
                    cellPadding: 5,
                },

                headStyles: {
                    fontSize: 12,
                    fontStyle: "bold",
                },

            });

            // Footer
            const finalY =
                doc.lastAutoTable?.finalY || 38;

            doc.setFontSize(10);

            doc.text(
                `Generated by Medlora`,
                14,
                finalY + 15
            );

            doc.save("Medlora_Hospital_Report.pdf");

            toast.success(
                "PDF Report Exported Successfully"
            );

        } catch (error) {

            console.error(
                "PDF Export Error:",
                error
            );

            toast.error(
                "Failed to Export PDF"
            );

        }

    };


    // =====================================================
    // Export Excel
    // =====================================================

    const exportExcel = () => {

        try {

            const data = [

                {
                    Category: "Total Users",
                    Value: report.totalUsers,
                },

                {
                    Category: "Total Doctors",
                    Value: report.totalDoctors,
                },

                {
                    Category: "Total Patients",
                    Value: report.totalPatients,
                },

                {
                    Category: "Total Appointments",
                    Value: report.totalAppointments,
                },

                {
                    Category: "Total Bills",
                    Value: report.totalBills,
                },

                {
                    Category: "Total Revenue",
                    Value: report.totalRevenue,
                },

                {
                    Category: "Paid Bills",
                    Value: report.paidBills,
                },

                {
                    Category: "Pending Bills",
                    Value: report.pendingBills,
                },

            ];


            const worksheet =
                XLSX.utils.json_to_sheet(data);


            // Column width
            worksheet["!cols"] = [
                {
                    wch: 28,
                },
                {
                    wch: 20,
                },
            ];


            const workbook =
                XLSX.utils.book_new();


            XLSX.utils.book_append_sheet(
                workbook,
                worksheet,
                "Medlora Report"
            );


            const excelBuffer =
                XLSX.write(workbook, {

                    bookType: "xlsx",

                    type: "array",

                });


            const file = new Blob(
                [excelBuffer],
                {
                    type:
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                }
            );


            saveAs(
                file,
                "Medlora_Hospital_Report.xlsx"
            );


            toast.success(
                "Excel Report Exported Successfully"
            );

        } catch (error) {

            console.error(
                "Excel Export Error:",
                error
            );

            toast.error(
                "Failed to Export Excel"
            );

        }

    };


    // =====================================================
    // Print Report
    // =====================================================

    const printReport = () => {

        window.print();

    };


    // =====================================================
    // Loading
    // =====================================================

    if (loading) {

        return <Loader />;

    }


    // =====================================================
    // UI
    // =====================================================

    return (

        <div className="reports-container">

            {/* =========================================
                HEADER
            ========================================= */}

            <div className="reports-header">

                <div>

                    <p className="reports-label">
                        MEDLORA ANALYTICS
                    </p>

                    <h1 className="report-title">
                        📊 Hospital Reports
                    </h1>

                    <p className="report-subtitle">
                        View, analyze and export your
                        hospital performance summary.
                    </p>

                </div>

            </div>


            {/* =========================================
                EXPORT BUTTONS
            ========================================= */}

            <div className="report-buttons">

                <button
                    type="button"
                    className="pdf-btn"
                    onClick={exportPDF}
                >
                    📄 Export PDF
                </button>


                <button
                    type="button"
                    className="excel-btn"
                    onClick={exportExcel}
                >
                    📊 Export Excel
                </button>


                <button
                    type="button"
                    className="print-btn"
                    onClick={printReport}
                >
                    🖨 Print Report
                </button>

            </div>


            {/* =========================================
                REPORT CARDS
            ========================================= */}

            <div className="report-cards">


                {/* Users */}

                <div className="report-card users">

                    <div className="report-card-icon">
                        👥
                    </div>

                    <div className="report-card-info">

                        <h2>
                            Total Users
                        </h2>

                        <h3>
                            {report.totalUsers}
                        </h3>

                    </div>

                </div>


                {/* Doctors */}

                <div className="report-card doctors">

                    <div className="report-card-icon">
                        👨‍⚕️
                    </div>

                    <div className="report-card-info">

                        <h2>
                            Total Doctors
                        </h2>

                        <h3>
                            {report.totalDoctors}
                        </h3>

                    </div>

                </div>


                {/* Patients */}

                <div className="report-card patients">

                    <div className="report-card-icon">
                        🧑
                    </div>

                    <div className="report-card-info">

                        <h2>
                            Total Patients
                        </h2>

                        <h3>
                            {report.totalPatients}
                        </h3>

                    </div>

                </div>


                {/* Appointments */}

                <div className="report-card appointments">

                    <div className="report-card-icon">
                        📅
                    </div>

                    <div className="report-card-info">

                        <h2>
                            Appointments
                        </h2>

                        <h3>
                            {report.totalAppointments}
                        </h3>

                    </div>

                </div>


                {/* Bills */}

                <div className="report-card bills">

                    <div className="report-card-icon">
                        💳
                    </div>

                    <div className="report-card-info">

                        <h2>
                            Total Bills
                        </h2>

                        <h3>
                            {report.totalBills}
                        </h3>

                    </div>

                </div>


                {/* Revenue */}

                <div className="report-card revenue">

                    <div className="report-card-icon">
                        💰
                    </div>

                    <div className="report-card-info">

                        <h2>
                            Total Revenue
                        </h2>

                        <h3>
                            ₹ {report.totalRevenue}
                        </h3>

                    </div>

                </div>


                {/* Paid */}

                <div className="report-card paid">

                    <div className="report-card-icon">
                        ✅
                    </div>

                    <div className="report-card-info">

                        <h2>
                            Paid Bills
                        </h2>

                        <h3>
                            {report.paidBills}
                        </h3>

                    </div>

                </div>


                {/* Pending */}

                <div className="report-card pending">

                    <div className="report-card-icon">
                        ⏳
                    </div>

                    <div className="report-card-info">

                        <h2>
                            Pending Bills
                        </h2>

                        <h3>
                            {report.pendingBills}
                        </h3>

                    </div>

                </div>

            </div>


            {/* =========================================
                HOSPITAL SUMMARY
            ========================================= */}

            <div className="report-table">

                <div className="summary-header">

                    <div>

                        <h2>
                            📋 Hospital Summary
                        </h2>

                        <p>
                            Complete hospital statistics
                        </p>

                    </div>

                </div>


                <div className="table-wrapper">

                    <table>

                        <thead>

                            <tr>

                                <th>
                                    Category
                                </th>

                                <th>
                                    Value
                                </th>

                            </tr>

                        </thead>


                        <tbody>

                            <tr>
                                <td>
                                    Total Users
                                </td>

                                <td>
                                    {report.totalUsers}
                                </td>
                            </tr>


                            <tr>
                                <td>
                                    Total Doctors
                                </td>

                                <td>
                                    {report.totalDoctors}
                                </td>
                            </tr>


                            <tr>
                                <td>
                                    Total Patients
                                </td>

                                <td>
                                    {report.totalPatients}
                                </td>
                            </tr>


                            <tr>
                                <td>
                                    Total Appointments
                                </td>

                                <td>
                                    {report.totalAppointments}
                                </td>
                            </tr>


                            <tr>
                                <td>
                                    Total Bills
                                </td>

                                <td>
                                    {report.totalBills}
                                </td>
                            </tr>


                            <tr>
                                <td>
                                    Total Revenue
                                </td>

                                <td>
                                    ₹ {report.totalRevenue}
                                </td>
                            </tr>


                            <tr>
                                <td>
                                    Paid Bills
                                </td>

                                <td>
                                    {report.paidBills}
                                </td>
                            </tr>


                            <tr>
                                <td>
                                    Pending Bills
                                </td>

                                <td>
                                    {report.pendingBills}
                                </td>
                            </tr>

                        </tbody>

                    </table>

                </div>

            </div>

        </div>

    );

}

export default Reports;